### ISSUE TITLE
Draft 04: Number of custom bits in Version 8 UUIDs

### ISSUE THREAD

**Issue by felipecrv** [uuid6/uuid6-ietf-draft#104]
# Change Proposal Template

#### Source (Select one.)
-  [ ] IETF Published Draft
-  [x] Work in Progress Draft

####  Change Reason (Select all that apply.)
- [x] Typos and grammatical issues
- [ ] Bad Reference
- [ ] IETF Verbiage modification (MAY, MUST, SHOULD, SHOULD NOT, etc)
- [ ] New Text for additional context
- [ ] Underlying XML Format Update
- [ ] ASCII diagram updates (artwork, code samples, etc.)  

####  Draft Number, Full Section, Name
```
Draft 04, Section 5.3 UUID Version 8
https://datatracker.ietf.org/doc/html/draft-peabody-dispatch-new-uuid-format-03
```

####  Current Text:
```
				The only explicitly defined bits are the Version and Variant leaving 120 bits
				for implementation specific time-based UUIDs.
```

#### Proposed Text:
```
				The only explicitly defined bits are the Version and Variant leaving 122 bits
				for implementation specific UUIDs.
```

---

### Other Supporting information below:

Changed the number of bits from 120 to 122 and removed "time-based" since vendor-specific UUIDs don't have to be time-based necessarily.

**Comment by kyzer-davis** [comment]
@philix, great catch. I will knock this out in draft 04!
