### ISSUE TITLE
The conditions for the use of source-generated UUIDs and receiver-generated UUIDs

### ISSUE THREAD

**Issue by sergeyprokhorenko** [uuid6/uuid6-ietf-draft#110]
# Change Proposal

#### Source (Select one.)
-  [ ] IETF Published Draft
-  [x] Work in Progress Draft

####  Change Reason (Select all that apply.)
- [ ] Typos and grammatical issues
- [ ] Bad Reference
- [ ] IETF Verbiage modification (MAY, MUST, SHOULD, SHOULD NOT, etc)
- [x] New Text for additional context
- [ ] Underlying XML Format Update
- [ ] ASCII diagram updates (artwork, code samples, etc.)  

####  Draft Number, Full Section, Name

Section 6.9.  [DBMS and Database Considerations](https://uuid6.github.io/uuid6-ietf-draft/#name-dbms-and-database-considera)

####  Current Text:

Applications using a monolithic database may find using database-generated UUIDs (as opposed to client-generate UUIDs) provides the best UUID monotonicity. In addition to UUIDs, additional identifiers MAY be used to ensure integrity and feedback.

#### Proposed Text:

If the data comes from remote sources (clients or distributed nodes), then each record MAY be stored with both source-generated UUID and receiver-generated UUID with very different timestamps to ensure integrity, feedback and best UUID monotonicity. But if integrity and feedback are not required, then receiver-generated UUIDs provide the best UUID monotonicity.

If the data comes from nearby sources, then source-generated UUIDs provide the best UUID integrity and feedback with sufficient monotonicity.

**Comment by kyzer-davis** [comment]
I am not 100% sure the proposed text provides anything more over the existing text.

- **Integrity and feedback**: I am not a fan of specifying that somebody generate a second UUID for every remote UUID since that is double the compute with little upside... or at least little upsides defined in the this text.
- **Remote vs Local**: IMO we already do a pretty good job of concisely stating the downsides local vs remote generation in the first line of the current text. The proposed text seems to split it into two sentences that more or less convey the same meaning as the original text.

**Comment by sergeyprokhorenko** [comment]
The proposed text is more detailed and gives more accurate instructions to database developers. It also adds the possibility to have two UUIDs if there are high requirements for monotony (this is not obligatory, but possible)

**Comment by kyzer-davis** [comment]
@sergeyprokhorenko, I see your point now about distributed node monotonicity and defining a way to ensure we have the best monotonic UUID in distributed node generation scenarios.

Coincidently I also received an email from the IETF mailer on the same topic of "Monotonicity guarantees with distributed nodes" which we don't define in the spec. 

As such I have steered some others to this thread. Hopefully we have more feedback on this specific topic and can come an agreement on a solution for this scenario.
