### ISSUE TITLE
Typo in UUIDv7 example value

### ISSUE THREAD

**Issue by kyzer-davis** [uuid6/uuid6-ietf-draft#123]
# Change Proposal Template

#### Source (Select one.)
-  [x] IETF Published Draft
-  [ ] Work in Progress Draft

####  Change Reason (Select all that apply.)
- [x] Typos and grammatical issues
- [ ] Bad Reference
- [ ] IETF Verbiage modification (MAY, MUST, SHOULD, SHOULD NOT, etc)
- [ ] New Text for additional context
- [ ] Underlying XML Format Update
- [ ] ASCII diagram updates (artwork, code samples, etc.)  

####  Draft Number, Full Section, Name
```
The timestamp is Tuesday, February 22, 2022 2:22:22.00 PM GMT-05:00
```

####  Current Text:
```
UUIDs MAY be universally unique.
```

#### Proposed Text:
```
The timestamp is Tuesday, February 22, 2022 14:22:22.00 PM GMT-05:00
```

---

### Other Supporting information below:
From: Ben Ramsey <ben@benramsey.com>
```
As I was working on some tests for an implementation, I came across what I think might be a typo in draft-peabody-dispatch-new-uuid-format-04, Appendix B.2:

    The timestamp is Tuesday, February 22, 2022 2:22:22.00 PM GMT-05:00
    represented as 0x17F22E279B0 or 1645557742000

The hex value mentioned does convert properly to 1645557742000. However, when converting 1645557742000 to seconds (1645557742), the timestamp evaluates to:

    Tuesday, February 22, 2022 14:22:22.00 PM GMT-05:00

See, for example, https://duckduckgo.com/?q=1645557742+unix+timestamp&t=osx&ia=answer&iax=answer

I think the time in the text should change from “2:22:22.00” to “14:22:22.00”.

Cheers,
Ben
```

**Comment by ramsey** [comment]
You may ignore and close this issue. There is no typo.

I missed the "PM" in the time string and thought the string meant 2 AM. Since "PM" is in the string, it is correct.

I feel quite silly now. Sorry for the churn. 😄 

```shell
❯ TZ='America/New_York' date --date='@1645557742' '+%A, %B %-d, %Y %-I:%M:%S %p GMT%:z'
Tuesday, February 22, 2022 2:22:22 PM GMT-05:00
```
