### ISSUE TITLE
Remove "time-based" constraint from version 8 UUID

### ISSUE THREAD

**Issue by broofa** [uuid6/uuid6-ietf-draft#124]
# Change Proposal Template

I should have caught this earlier, but is there a reason version 8 UUIDs are described as being for "time-based" UUIDs specifically?   I see version 8 as being the catch-all format for *any* type of experimental UUID, and I'm fairly certain it's going to be used as such, regardless of whether it's described as "time-based" or not.

#### Source (Select one.)
-  [X] IETF Published Draft
-  [ ] Work in Progress Draft

####  Change Reason (Select all that apply.)
- [ ] Typos and grammatical issues
- [ ] Bad Reference
- [ ] IETF Verbiage modification (MAY, MUST, SHOULD, SHOULD NOT, etc)
- [X] New Text for additional context
- [ ] Underlying XML Format Update
- [ ] ASCII diagram updates (artwork, code samples, etc.)  

####  Draft Number, Full Section, Name
draft-ietf-uuidrev-rfc4122bis-00, Section [5.8. ](https://www.ietf.org/archive/id/draft-ietf-uuidrev-rfc4122bis-00.html#section-5.8)[UUID Version 8](https://www.ietf.org/archive/id/draft-ietf-uuidrev-rfc4122bis-00.html#name-uuid-version-8)

####  Current Text:
```
The only explicitly defined bits are the Version and Variant leaving 122 bits for implementation specific time-based UUIDs. 
```

#### Proposed Text:
```
The only explicitly defined bits are the Version and Variant leaving 122 bits for implementation-specific UUIDs. 
```

---

### Other Supporting information below:
Insert data here

**Comment by kyzer-davis** [comment]
Good catch, Ill slate it for Draft 01 of rfc4122biz.
