### ISSUE TITLE
Further clarify v7 field description

### ISSUE THREAD

**Issue by LiosK** [uuid6/uuid6-ietf-draft#125]
# Change Proposal Template

#### Source (Select one.)

- [x] IETF Published Draft
- [ ] Work in Progress Draft

#### Change Reason (Select all that apply.)

- [ ] Typos and grammatical issues
- [ ] Bad Reference
- [ ] IETF Verbiage modification (MAY, MUST, SHOULD, SHOULD NOT, etc)
- [x] New Text for additional context
- [ ] Underlying XML Format Update
- [ ] ASCII diagram updates (artwork, code samples, etc.)

#### Draft Number, Full Section, Name

```
rfc4122bis/00; 5.7. UUID Version 7; Figure 11: UUIDv7 Field and Bit Layout
```

#### Current Text:

unix_ts_ms:

48 bit big-endian unsigned number of Unix epoch timestamp as per Section 6.1.

(snip)

rand_a:

12 bits pseudo-random data to provide uniqueness as per <del>Section 6.2 and</del> Section 6.8.

(snip)

rand_b:

The final 62 bits of pseudo-random data to provide uniqueness as per <del>Section 6.2 and</del> Section 6.8.

#### Proposed Text:

unix_ts_ms:

48 bit big-endian unsigned number of Unix epoch timestamp <ins>in milliseconds</ins> as per Section 6.1.

(snip)

rand_a:

12 bits pseudo-random data to provide uniqueness as per Section 6.8 <ins>and/or optional counter to guarantee additional monotonicity as per Section 6.2</ins>.

(snip)

rand_b:

The final 62 bits of pseudo-random data to provide uniqueness as per Section 6.8 <ins>and/or optional counter to guarantee additional monotonicity as per Section 6.2</ins>.

---

### Other Supporting information below:

I have recently noticed some readers misread and are confused by the UUIDv7 spec. Particularly, they believe `unix_ts_ms` accepts any of millisecond, microsecond, and nanosecond timestamps and `rand_a` and `rand_b` are dedicated to random data only. We can be clearer and more specific by adding some words to the field description just below the bit layout figure.

**Comment by LiosK** [comment]
Should I post this to https://github.com/ietf-wg-uuidrev/rfc4122bis/issues ? Perhaps, it would be helpful if the new repository had a similar change proposal template.

**Comment by kyzer-davis** [comment]
Seems logical enough to me. I am always down for further clarification so folks don't need to assume.
Also I am fine with posts here or over on that repo. I am watching both repos and the IETF mailer for changes to compile between drafts.

I'll slate this for Draft 01 of the biz doc and add it to my EITF 115 talking points.

**Comment by LiosK** [comment]
Alternatively, we can add several paragraphs below the bit layout figure to describe the spec using BCP 14 keywords like:

> The `unix_ts_ms` field MUST be dedicated to a 48-bit big-endian unsigned integer representing Unix epoch millisecond timestamp as per Section 6.1. The 12-bit `rand_a` and 62-bit `rand_b` fields, jointly, MUST be filled with one of the following data:
>
> 1. pseudo-random data as per Section 6.8;
> 2. a big-endian unsigned integer representing fixed-length dedicated counter as per Section 6.2, with the remaining bits being padded with pseudo-random data as per Section 6.8; or,
> 3. a big-endian unsigned integer representing monotonic random counter as per Section 6.2.
