### ISSUE TITLE
JSONB format for UUID

### ISSUE THREAD

**Issue by sergeyprokhorenko** [uuid6/uuid6-ietf-draft#37]
The exhausting attempts to squeeze such a heterogeneous functionality into 128 bits gave me the seditious thought of JSONB format as a container for UUID. See https://postgrespro.com/docs/postgresql/13/datatype-json for JSONB format. It is binary and indexable.

**Comment by kyzer-davis** [comment]
Formatting, bit-length change, and Encoding are out of scope for this RFC. Marking off topic and closing to clean up the issue tracker due to little discussion about this one in particular.
