### ISSUE TITLE
UUIDv7: Is "the node MUST NOT be set to all 0s" necessary?

### ISSUE THREAD

**Issue by oittaa** [uuid6/uuid6-ietf-draft#45]
https://datatracker.ietf.org/doc/html/draft-peabody-dispatch-new-uuid-format-02#section-4.4.3

>    The UUIDv7 Node MAY
>    contain any set of data an implementation desires however the node
>    MUST NOT be set to all 0s which does not ensure global uniqueness.
>    In most scenarios the node SHOULD be filled with pseudo-random data.

Is that necessary? It creates a special case in pretty much every programming language.

For example in Python you have to create a node with something like the following.
```
node = 0
while node == 0:
    node = secrets.randbits(56)
```
Instead of just writing.

```
node = secrets.randbits(56)
```

**Comment by fabiolimace** [comment]
I agree. I think removing that phrase improves the text.

**Comment by kyzer-davis** [comment]
Yeah, that makes sense. I can add it to the list of items to change in my Draft 03 pass of UUIDv7.
