### ISSUE TITLE
Quantum-mechanical TRNG or CSPRNG is a must

### ISSUE THREAD

**Issue by sergeyprokhorenko** [uuid6/uuid6-ietf-draft#55]
[Quantum-mechanical TRNG](https://en.wikipedia.org/wiki/Hardware_random_number_generator#Quantum_random_properties) or [CSPRNG](https://en.wikipedia.org/wiki/Cryptographically-secure_pseudorandom_number_generator) is a must.

It means secrets.randbits() for Python and crypto/rand for Golang

**Comment by broofa** [comment]
See also https://github.com/uuid6/uuid6-ietf-draft/issues/33#issuecomment-902124684

**Comment by peterbourgon** [comment]
The entropy source is a decision for the user, not the specification. High-quality entropy is often cost-prohibitive.
