### ISSUE TITLE
Draft 03: Increase the maximum counter bit-length to 42

### ISSUE THREAD

**Issue by fabiolimace** [uuid6/uuid6-ietf-draft#93]
# Change Proposal Template

#### Source (Select one.)
-  [ ] IETF Published Draft
-  [x] Work in Progress Draft

####  Change Reason (Select all that apply.)
- [ ] Typos and grammatical issues
- [ ] Bad Reference
- [ ] IETF Verbiage modification (MAY, MUST, SHOULD, SHOULD NOT, etc)
- [x] New Text for additional context
- [ ] Underlying XML Format Update
- [ ] ASCII diagram updates (artwork, code samples, etc.)  

####  Draft Number, Full Section, Name
```
6.2.  Monotonicity and Counters - Fixed-Length Dedicated Counter Length
```

####  Current Text:
```
General guidance is that the counter SHOULD be at least 12 bits but no longer than 40 bits.
```

#### Proposed Text:
```
General guidance is that the counter SHOULD be at least 12 bits but no longer than 42 bits.
```

---

### Other Supporting information below:
This is a suggestion to increase the maximum counter bit-length from 40 to 42. This leaves 32 bits left for entropy, which is perfect 32-bit random number generators. (128-**6**-48-**42** = 32). The number 40 made sense in version 7E (128-**8**-48-**40** = 32).

Permalink: https://github.com/uuid6/uuid6-ietf-draft/blob/5672be7bf730840643fcd2537424330d28831c5d/draft-peabody-dispatch-new-uuid-format-03.txt#L826

**Comment by LiosK** [comment]
+1 to this proposal!
