### ISSUE TITLE
Incorrect timestamp in "Example of a UUIDv7 Value"

### ISSUE THREAD

**Issue by nerg4l** [uuid6/uuid6-ietf-draft#99]
# Change Proposal Template

#### Source (Select one.)
-  [x] IETF Published Draft
-  [ ] Work in Progress Draft

####  Change Reason (Select all that apply.)
- [x] Typos and grammatical issues
- [ ] Bad Reference
- [ ] IETF Verbiage modification (MAY, MUST, SHOULD, SHOULD NOT, etc)
- [ ] New Text for additional context
- [ ] Underlying XML Format Update
- [ ] ASCII diagram updates (artwork, code samples, etc.)  

####  Draft Number, Full Section, Name
```
Draft 03, Section B.2 Example of a UUIDv7 Value
```

####  Current Text:
```
   The timestamp is Tuesday, February 22, 2022 2:22:22.00 PM GMT-05:00
   represented as 0x17F21CFD130 or 1645539742000

   -------------------------------
   field      bits    value
   -------------------------------
   unix_ts_ms   48    0x017F21CFD130
   var           4    0x7
   rand_a       12    0xCC3
   var           2    b10
   rand_b       62    0x18C4DC0C0C07398F
   -------------------------------
   total       128
   -------------------------------
   final: 017F21CF-D130-7CC3-98C4-DC0C0C07398F
```

#### Proposed Text:
```
   The timestamp is Tuesday, February 22, 2022 2:22:22.00 PM GMT-05:00
   represented as 0x17F22E279B0 or 1645557742000

   -------------------------------
   field      bits    value
   -------------------------------
   unix_ts_ms   48    0x017F22E279B0
   var           4    0x7
   rand_a       12    0xCC3
   var           2    b10
   rand_b       62    0x18C4DC0C0C07398F
   -------------------------------
   total       128
   -------------------------------
   final: 017F22E2-79B0-7CC3-98C4-DC0C0C07398F
```

---

### Other Supporting information below:
- Currently displayed representation `0x17F21CFD130`/`1645539742000` happens to be Tuesday, February 22, 2022 2:22:22.00 PM GMT+00:00
- Currently displayed timestamp Tuesday, February 22, 2022 2:22:22.00 PM GMT-05:00 happens to be `0x17F22E279B0`/`1645557742000`

https://play.golang.com/p/gGqHpUuM7Hh

**Comment by kyzer-davis** [comment]
@nerg4l, good catch. 

I must have grabbed GMT+0 from one place then assumed GMT+5 (my timeszone) when writing!
